name: Lint Docker Compose

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  dclint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker-compose-linter/dclint-github-action/docker-action@v1.3.0
        with:
          args: '[".", "-r", "--debug", "-f", "github"]'
