name: Lint Docker Compose

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  dclint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker-compose-linter/dclint-github-action@v1.2.0
        with:
          path: .
          recursive: true
