name: Lint Docker Compose

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  dclint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dclint
        uses: docker-compose-linter/dclint-github-action/reviewdog-action@v1.3.0
        with:
          reporter: 'github-pr-review'
